* 剪切和存储文本
* Menu:
  当你用'kill命令剪切或删除掉缓存（buffer）中的一段文本内容时。这段内容将会被保存在list中，你可以使用'yank命令召回他。
** Storing Text
   emacs用一个list来管理被存储的文本串。通过使用'car和'nthcdr函数，我们就可以检索list中的文本串。
  eg:
  (car (nthcdr 1 '("another piece"
                      "a piece of text"
                      "previous piece")))
          => "a piece of text"
  这个list被称为”kill ring“，本章主要就是讲解这个kill ring的用法的。
** zap-to-char
*** Complete zap-to-char
    'zap-to-char函数的功能是删除从指定光标位置起到指定字符（可以通过传递数字参数来确定是指定字符的第几个）处之间的文本内容。
    被删除后的文本将会被放在kill ring中去。我们可以通过输入'C-y('yank)来召回被删除的文本内容.
    如果被指定的字符并不存在，'zap-to-char将会给我们"Search failed"的提示。
    下面是函数的完整实现:
    (defun zap-to-char (arg char)
       "Kill up to and including ARG'th occurrence of CHAR.
     Case is ignored if `case-fold-search' is non-nil in the current buffer.
     Goes backward if ARG is negative; error if CHAR not found."
       (interactive "p\ncZap to char: ")
       (if (char-table-p translation-table-for-input)
           (setq char (or (aref translation-table-for-input char) char)))
       (kill-region (point) (progn
                              (search-forward (char-to-string char)
                                              nil nil arg)
                              (point))))
*** zap-to-char-interactive
       p代表一个前缀数值参数，c代表一个字符操作。
       如果'zap-to-char是在一个只读buffer中使用，那么该函数只能将文本复制到kill ring，而不能删除它。
       echo 区域讲会给出该buffer仅只读的提示。
*** zap-to-char body
    'char-table-p 判断检查输入的参数是否在参数表中，如果存在的话，将会把char 赋值为char参数表中的一个字符值。
    'aref 从数组列表中提取值。
    'progn
    'search-forward
*** search-forward
    'char-to-string将字符作为字符串看待。下面我们来看'search-forward这个函数
    第一个参数必须是一个字符串，它是我们搜索的目标。
    第二个参数是设定字符串搜索的界限，这里为nil代表搜索界限为整个buffer。
    第三个参数告诉函数如果搜索失败的话，将会怎么做。nil将会使函数发出一个错误信号来告诉emacs。
    第四个参数告诉函数要搜寻的字符串重复的次数，该参数为可选参数。如果该参数不存在的话，则默认值为1，如果参数默认值为负的话。搜索将会往前搜索。
    ’search-forward函数的摸板如下所示：
     (search-forward "TARGET-STRING"
                     LIMIT-OF-SEARCH
                     WHAT-TO-DO-IF-SEARCH-FAILS
                     REPEAT-COUNT)
*** progn
    'progn使它的每一个参数表达式按顺序执行，并将最后一个表达式的返回值返回。
    'progn的模板如下所示。
    (progn
    BODY...)
*** Summing up zap-to-char
** kill-region
   'zap-to-char函数使用到了'kill-region函数，该函数从一段区域中剪切文本，并将这段文本保存在 kill ring中。
   我们则可以通过它来还原我们删除掉的文本。
   'kill-region将会使用'condition-case和'copy-region-as-kill函数这两个我们都会在下面详加解释
*** Complete kill-region
               完整的函数定义如下所示:
	       (defun kill-region (beg end)
	       "Kill (\"cut\") text between point and mark.
	       This deletes the text from the buffer and saves it in the kill ring.
	       The command \\[yank] can retrieve it from there. ... "

	       ;; * Since order matters, pass point first.
	       (interactive (list (point) (mark)))
	       ;; * And tell us if we cannot cut the text.
	       ;; `unless' is an `if' without a then-part.
	       (unless (and beg end)
               (error "The mark is not set now, so there is no region"))
	       
	       ;; * `condition-case' takes three arguments.
	       ;;    If the first argument is nil, as it is here,
	       ;;    information about the error signal is not
	       ;;    stored for use by another function.
	       (condition-case nil

               ;; * The second argument to `condition-case' tells the
               ;;    Lisp interpreter what to do when all goes well.

               ;;    It starts with a `let' function that extracts the string
               ;;    and tests whether it exists.  If so (that is what the
               ;;    `when' checks), it calls an `if' function that determines
               ;;    whether the previous command was another call to
               ;;    `kill-region'; if it was, then the new text is appended to
               ;;    the previous text; if not, then a different function,
               ;;    `kill-new', is called.

               ;;    The `kill-append' function concatenates the new string and
               ;;    the old.  The `kill-new' function inserts text into a new
               ;;    item in the kill ring.

               ;;    `when' is an `if' without an else-part.  The second `when'
               ;;    again checks whether the current string exists; in
               ;;    addition, it checks whether the previous command was
               ;;    another call to `kill-region'.  If one or the other
               ;;    condition is true, then it sets the current command to
               ;;    be `kill-region'.
               (let ((string (filter-buffer-substring beg end t)))
               (when string                    ;STRING is nil if BEG = END
               ;; Add that string to the kill ring, one way or another.
               (if (eq last-command 'kill-region)
               ;;    - `yank-handler' is an optional argument to
                   ;;    `kill-region' that tells the `kill-append' and
                   ;;    `kill-new' functions how deal with properties
                   ;;    added to the text, such as `bold' or `italics'.
                   (kill-append string (< end beg) yank-handler)
                   (kill-new string nil yank-handler)))
		   (when (or string (eq last-command 'kill-region))
		   (setq this-command 'kill-region))
		   nil)
		   
		   ;;  * The third argument to `condition-case' tells the interpreter
		   ;;    what to do with an error.
		   ;;    The third argument has a conditions part and a body part.
		   ;;    If the conditions are met (in this case,
		   ;;             if text or buffer are read-only)
		   ;;    then the body is executed.
		   ;;    The first part of the third argument is the following:
		   ((buffer-read-only text-read-only) ;; the if-part
		   ;; ...  the then-part
		   (copy-region-as-kill beg end)
		   ;;    Next, also as part of the then-part, set this-command, so
		   ;;    it will be set in an error
		   (setq this-command 'kill-region)
		   ;;    Finally, in the then-part, send a message if you may copy
		   ;;    the text to the kill ring without signaling an error, but
		   ;;    don't if you may not.
		   (if kill-read-only-ok
		   (progn (message "Read only text copied to kill ring") nil)
		   (barf-if-buffer-read-only)
		   ;; If the buffer isn't read-only, the text is.
		   (signal 'text-read-only (list (current-buffer)))))))
*** condition-case
                (condition-case
		VAR
		BODYFORM
		ERROR-HANDLER...)
		condition-case可以支持错误处理。
		第三部分错误处理部分不太理解，暂时搁置。
*** Lisp macro
              上面的'kill-region函数中的'when表达式是一个Lisp宏。它相当于一种没有else的if结构。Lisp宏能够使你定义一种新的结构和一些其他语言特性。
	      'unless表达式也是一个宏，它和when相反，是一个没有then 的if结构。
	      
** copy-region-as-kill
                当你调用'copy-region-as-kill函数时是在调用'kill-region之后，emacs将会追加之前复制的文本到之后复制的文本之后。
		这意味着如果你用'yank命令召回之前的文本时，你将会把两个函数删除掉的文本内容一起召回。而且在一些特殊情况下一些其他命令如果在'copy-region-as-kill之前
		使用的话，该函数将会复制文本已一种独特的形式存储到kill  ring 中去。
*** Complete copy-region-as-kill
                函数定义实现如下:
		(defun copy-region-as-kill (beg end)
		"Save the region as if killed, but don't kill it.
		In Transient Mark mode, deactivate the mark.
		If `interprogram-cut-function' is non-nil, also save the text for a window
		system cut and paste."
		(interactive "r")
		(if (eq last-command 'kill-region)
		(kill-append (filter-buffer-substring beg end) (< end beg))
		(kill-new (filter-buffer-substring beg end)))
		(if transient-mark-mode
		(setq deactivate-mark t))
		nil)
		* 
		  (if transient-mark-mode
		(setq deactivate-mark t))
		这两行代码的意思是如果Transient Mark mode被开启的话，那么就阻止该复制区域被高亮显示。
*** copy-region-as-kill body
**** last-command & this-command
          last-command
	  this-command
	  这里需要注意的是如果上一个命令是'kill-region的话,那么我们将使用'kill-append函数将的得到的字符串，链接到kill ring 中最后一个string中去。
	  如果不是的话，我们就是使用'kill-new函数将得到的字符串，作为一个新的元素，添加到kill ring 中去。
**** kill-append function
     函数实体:
     (defun kill-append (string before-p &optional yank-handler)
       "Append STRING to the end of the latest kill in the kill ring.
     If BEFORE-P is non-nil, prepend STRING to the kill.
     ... "
       (let* ((cur (car kill-ring)))
         (kill-new (if before-p (concat string cur) (concat cur string))
                   (or (= (length cur) 0)
                       (equal yank-handler
                              (get-text-property 0 'yank-handler cur)))
                   yank-handler)))

	 concat 函数演示 ：它可以用来修改列表中的string
	 (concat "abc" "def")
          => "abcdef"
	  (concat "new "
             (car '("first element" "second element")))
             => "new first element"
	  (concat (car
             '("first element" "second element")) " modified")
          => "first element modified"
**** kill-new function
        函数实体:
	(defun kill-new (string &optional replace yank-handler)
       "Make STRING the latest kill in the kill ring.
     Set `kill-ring-yank-pointer' to point to it.

     If `interprogram-cut-function' is non-nil, apply it to STRING.
     Optional second argument REPLACE non-nil means that STRING will replace
     the front of the kill ring, rather than being added to the list.
     ..."
       (if (> (length string) 0)
           (if yank-handler
               (put-text-property 0 (length string)
                                  'yank-handler yank-handler string))
         (if yank-handler
             (signal 'args-out-of-range
                     (list string "yank-handler specified for empty string"))))
       (if (fboundp 'menu-bar-update-yank-menu)
           (menu-bar-update-yank-menu string (and replace (car kill-ring))))
       (if (and replace kill-ring)
           (setcar kill-ring string)
         (push string kill-ring)
         (if (> (length kill-ring) kill-ring-max)
             (setcdr (nthcdr (1- kill-ring-max) kill-ring) nil)))
       (setq kill-ring-yank-pointer kill-ring)
       (if interprogram-cut-function
           (funcall interprogram-cut-function string (not replace))))
	     'kill-new函数的主要的作用就是插入新的文本串或者替换文本串，在kill ring 中。
	     'push将其第一个参数值放置到第二个参数值中去。下面这两个函数与'push函数具有同样的意义
	     (setq kill-ring (cons string kill-ring))
	     (add-to-list kill-ring string)
	     'kill-ring-yank-pointer是一个全局变量，用来和'kill-ring进行绑定。
	     'foundp  检测第一个参数是否是一个存在的函数。如果存在的话返回true。
	     ’menu-bar-update-yank-menu 是emacs中的 Edit item下的一个菜单条目。你可以通过鼠标进行操作选择。
	     'funcall 调用第一个参数中的函数，并将其他的参数作为第一个参数函数的参数。
	     'interprogram-cut-function 该变量操纵一个函数用来和其他操作系统进行交互。
** Digression into c
              在前面的'copy-region-as-kil函数中,我们用到了'filter-buffer-substring函数，而该函数又调用了 'delete-and-extract-region
	      这个函数。
	      ‘delete-and-extract-region这个函数是用c语言编写的。它是emacs系统的一个基本函数，我们下面就来讨论下该函数的实现
	      该函数是用c的宏实现的。
	      下面是宏的模版代码：
	         DEFUN ("delete-and-extract-region", Fdelete_and_extract_region,
		 Sdelete_and_extract_region, 2, 2, 0,
		 doc: /* Delete the text between START and END and return it.  */)
		 (Lisp_Object start, Lisp_Object end)
		 {
		 validate_region (&start, &end);
		 if (XINT (start) == XINT (end))
		 return empty_unibyte_string;
		 return del_range_1 (XINT (start), XINT (end), 1, 1);
		 }
		 该DEFUN分为七个部分:
		 * 第一部分是在Lisp中的函数名。
		 * 第二部分是在c中的函数名。
		 * 第三部分是c的常量结构。
		 * 第四第五部分指定最大,最小两个参数,该函数明确地需要两个参数。
		 * 剩下的就是func body。
		 validate_region 检查参数值是否是正确的类型，或者说在在一定范围内。如果start和end两个值
		 相等，就返回一个空字符串。
		 del_range_1删除实际的文本内容。
** defvar
                这节主要讲述'kill-ring变量如何用'defvar创造和初始化。
		'defvar与'setq一样给一个变量设置值。但它和'setq有两点不同:
		* ’defvar仅仅在变量没有被设置任何值的时候给其赋值（也就是初始化)，如果该变量已经有值得话，变量将不会被赋予任何值。
		* ‘defvar有 文档字符串。
*** See variable current value
               看变量当前值
               (defvar kill-ring nil
	       "List of killed text sequences.
	       ...")
*** defvar and asterisk
                 当你用'defvar指定一个变量的话，你是可以临时的改变变量的值的。
                 (defvar shell-command-default-error-buffer nil
		 "*Buffer name for `shell-command' ... error output.
		 ... ")
		 你可以用'set-variable 命令来 改变 'shell-command-default-error-buffer临时的。然而这些变量值只能在会话期起作用。
		 每次 Emacs重启的时候，它都会读取原先被初始化的值，除非你在你的.emacs进行过初始化设置。
** cons & search-fwd Review
              本章总结:
	      * 'car返回列表的第一个元素，'cdr返回第二个以及随后的元素列表。
		  eg: 
		  (car '(1 2 3 4 5 6 7))
		  => 1
                  (cdr '(1 2 3 4 5 6 7))
                 => (2 3 4 5 6 7)
	      * cons 将第一个参数和第二个参数构造在一起。
		eg:
		(cons 1 '(2 3 4))
               => (1 2 3 4)
	      * 'funcall将把它的第一个参数作为函数来执行，它将把它余下的参数传递给第一个参数。
	      * ’nthcdr 返回对一个list执行n次 cdr后所返回的结果值。
		eg：
		 (nthcdr 3 '(1 2 3 4 5 6 7))
		=> (4 5 6 7)
	      * 'setcar 改变list中的第一个元素值，‘setcdr改变list中第二个以及随后的列表。
		eg：
		(setq triple '(1 2 3))
                (setcar triple '37)
                triple
		=> (37 2 3)
               (setcdr triple '("foo" "bar"))
               triple
               => (37 "foo" "bar")
	      * ’progn 执行序列中的每个参数，并将最后一个值作为结果返回。
		eg：
		(progn 1 2 3 4)
		=>4
	      * 'save-restriction 记录当前缓存中narrowing中的区域，并在执行完该表达式后返回。
	      * ‘search-forward 搜索一个字符串，如果字符串存在的话，移动光标。如果用到正则表达式的话，用类似的函数're-search-forward.
		这两个函数需要四个参数。
		1. 要搜索的字符串或者高亮表达式。
		2. 可选的，搜索的限制。
		3. 可选的，如果搜索失败返回什么。
		4. 可选的，重复搜索多少次，如果参数为负则前向搜索。
	      * ’kill-region，从buffer中剪裁文本并保存到kill ring 中。这你就可以用‘yank返回结果。
	      * ’copy-region-as-kill 复制point和mark之间的文本到kill ring 中。
	      * ‘delete-and-extract-region 删除point和mark之间的文本，如果删除后，你将不能够再返回它了。
** searching Exercises
***  
     1.
     (defun test-search (str &optional arg)
     "Write an interactive function that searches for a string.  If the
     search finds the string, leave point after it and display a message"
     (interactive "stest-search the string: ")
     (let  ()
     (when str
     (when  (search-forward str nil (message "%s" "not Found!") arg)
     (message "%s" "Found!")))))
*** 
     2.
       (defun third-kill-ring ()
	 (let ((third-current-element  (car (nthcdr 2 kill-ring))))
	   (if   t
	      (message "the third element in kill-ring is %s" third-current-element) 
	     (message "the third element is not exist"))))
       # 该函数有问题，暂不明原因。
