#+TITLE: Linux 常用知识

*  一些Linux知识
    file， df， free，less，ln,
** 常用的命令
   1. type 显示命令的类型
    : type ls
   2. which 显示可执行程序的位置
     : which ls
   3.  使用别名创建自己的命令
        ; 号可以支持在命令终端 输入多条命令例如
       : cd /usr; ls ; cd -
       而我们可以用alias给组合命令起个别名已来调用。
       #+BEGIN_EXAMPLE
       type foo   ;如果 foo 命令已存在在linux中，则需更换命令名
       cd /usr; ls ; cd -
       alias foo='cd /usr; ls ; cd -'
       #+END_EXAMPLE

** tar 常用命令
    .bz2文件操作
    # tar -cjf all.tar.bz2 *.jpg 
  　#  tar -xjf all.tar.bz2 
   /etc下是系统层面的配置文件这里有几个有趣的文件
** /etc/crontab 定义了自动化运行的时间
** /etc/passwd 用户账户列表
   每行有七个成分，分别如下。
   用户名:口令:用户标识号:组标识号:注释性描述:主目录:登录Shell
   eg:
   root:x:0:0:root:/root:/bin/bash
   daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
   bin:x:2:2:bin:/bin:/usr/sbin/nologin
   这里我们说一下用户标识号,root的标示号为0，系统管理的账号为1-99,组标识号则存在/etc/group中

** /etc/fstab 存储设备以及相关挂载点的列表
** 通配符
    × 匹配任意多个字符 (包括 0和1）
   ？匹配任一单个字符(不包括0个)
    [characters]  匹配任意一个属于字符集的字符。
    [!characters] 匹配任意一个不属于字符集的字符。
    [ [ : class :]] 匹配任意一个属于指定字符类的字符。
 
    常用字符类:
    [:alnum:]  任意字母和u数字
    [;alpha:]  任意一个字母
    [:digit]  任意一个数字
    [:lower:]  任意小写字母
    [:upper:]  任意大写字母
** tcpdump 网络抓包
   * 抓本地回环接口数据包端口号为7697
   ： tcpdump -i lo  port 7697
** I/O重定向
*** grep  pattern [file ....]
    -i 选项，使grep不区分大小写。
    -v使grep只输出不匹配的选项
** 配置与环境
*** printenv:   
    这个只显示中所有的环境变量，而set还会包括shell变量，和shell 函数。
*** set:
*** export:
*** alias
    查看 别名
    ～/.bashrc 和~/.bash_profile都是用户的启动文件，但是前者是基于non-login shell的 而后者则是基于login-shell的。
    source .bashrc
    使环境变量直接生效。
**  文件搜索
** shell 脚本
   * 算术表达式
      格式如下: $((expression)) 算术表达式只支持整数不支持小数，如：
     ： echo $(($((5**2)) * 3)) 空格在算术表达式重视没有意义的，所以你可以任意的嵌套。
   * 双引号(soft quote)
     #+BEGIN_EXAMPLE
       考虑 两个例子的区别
       : echo $(cal)
       : echo "$(cal)"
    #+END_EXAMPLE
   * 单引号
     #+BEGIN_EXAMPLE
      several examples:
      /1. echo text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER/
     /2.  echo "text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER"/
     /3.  'echo text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER'/
     #+END_EXAMPLE
   * 转义字符
     \ 可以屏蔽特殊字符的意思
     ： echo " balance is \$5.00"
   * shell 变量。
      常量要大写，非常量则需要小写
     变量赋值时是可以扩展为字符串的任意值。
     eg:
           a=z
	   b="a string"
	   c="a string and $b"
	   d=$(ls-l foo.txt)
	   e=$((5*7))
	   f="\t\ta string\n"
   * if语句
     if commands; then
                   commands
     [elif     commands; then
                    commands....]
     [else 
                 commands]
     fi
   * test 表达式
     [ expression ]
     command1 && command2
     command1 || command2

     





     

   + 

   
   
